"""Add subscription billing foundation.

Revision ID: 0d5d642cec16
Revises: b6a204c731ef
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0d5d642cec16"
down_revision = "b6a204c731ef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "plans",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "code",
            sa.String(32),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "monthly_price_cents",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "annual_price_cents",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "invoice_checks_limit",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "invoice_checks_grace",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "users_limit",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "documents_limit",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "api_access",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "audit_logs",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "invoice_checks_limit >= 0",
            name="ck_plans_invoice_checks_limit",
        ),
        sa.CheckConstraint(
            "invoice_checks_grace >= 0",
            name="ck_plans_invoice_checks_grace",
        ),
        sa.CheckConstraint(
            "users_limit > 0",
            name="ck_plans_users_limit",
        ),
        sa.CheckConstraint(
            "documents_limit >= 0",
            name="ck_plans_documents_limit",
        ),
        sa.UniqueConstraint(
            "code",
            name="uq_plans_code",
        ),
    )

    op.create_table(
        "subscriptions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "organizations.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "plan_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "plans.id",
                ondelete="RESTRICT",
            ),
            nullable=False,
        ),
        sa.Column(
            "scheduled_plan_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "plans.id",
                ondelete="RESTRICT",
            ),
            nullable=True,
        ),
        sa.Column(
            "provider",
            sa.String(32),
            nullable=False,
            server_default="paddle",
        ),
        sa.Column(
            "provider_customer_id",
            sa.String(128),
            nullable=True,
        ),
        sa.Column(
            "provider_subscription_id",
            sa.String(128),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(32),
            nullable=False,
        ),
        sa.Column(
            "billing_interval",
            sa.String(16),
            nullable=True,
        ),
        sa.Column(
            "current_period_start",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "current_period_end",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "cancel_at_period_end",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "trial_started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "trial_ends_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "read_only_until",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "past_due_since",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "grace_period_ends_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "status IN ("
            "'trialing', "
            "'active', "
            "'past_due', "
            "'canceled', "
            "'read_only'"
            ")",
            name="ck_subscriptions_status",
        ),
        sa.CheckConstraint(
            "billing_interval IS NULL OR "
            "billing_interval IN ('monthly', 'annual')",
            name="ck_subscriptions_billing_interval",
        ),
        sa.UniqueConstraint(
            "organization_id",
            name="uq_subscriptions_organization_id",
        ),
        sa.UniqueConstraint(
            "provider_subscription_id",
            name="uq_subscriptions_provider_subscription_id",
        ),
    )

    op.create_index(
        "ix_subscriptions_organization_id",
        "subscriptions",
        ["organization_id"],
    )
    op.create_index(
        "ix_subscriptions_provider_customer_id",
        "subscriptions",
        ["provider_customer_id"],
    )
    op.create_index(
        "ix_subscriptions_status",
        "subscriptions",
        ["status"],
    )

    op.create_table(
        "subscription_usage",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "subscription_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "subscriptions.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "organizations.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "period_start",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "period_end",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "invoice_checks_used",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "invoice_checks_used >= 0",
            name="ck_subscription_usage_invoice_checks_used",
        ),
        sa.CheckConstraint(
            "period_end > period_start",
            name="ck_subscription_usage_period",
        ),
        sa.UniqueConstraint(
            "subscription_id",
            "period_start",
            name="uq_subscription_usage_period",
        ),
    )

    op.create_index(
        "ix_subscription_usage_organization_id",
        "subscription_usage",
        ["organization_id"],
    )
    op.create_index(
        "ix_subscription_usage_subscription_id",
        "subscription_usage",
        ["subscription_id"],
    )

    op.create_table(
        "billing_events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.String(32),
            nullable=False,
            server_default="paddle",
        ),
        sa.Column(
            "provider_event_id",
            sa.String(128),
            nullable=False,
        ),
        sa.Column(
            "event_type",
            sa.String(128),
            nullable=False,
        ),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "organizations.id",
                ondelete="SET NULL",
            ),
            nullable=True,
        ),
        sa.Column(
            "subscription_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "subscriptions.id",
                ondelete="SET NULL",
            ),
            nullable=True,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(),
            nullable=False,
        ),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "provider",
            "provider_event_id",
            name="uq_billing_events_provider_event",
        ),
    )

    op.create_index(
        "ix_billing_events_organization_id",
        "billing_events",
        ["organization_id"],
    )
    op.create_index(
        "ix_billing_events_subscription_id",
        "billing_events",
        ["subscription_id"],
    )
    op.create_index(
        "ix_billing_events_event_type",
        "billing_events",
        ["event_type"],
    )


def downgrade() -> None:
    op.drop_table("billing_events")
    op.drop_table("subscription_usage")
    op.drop_table("subscriptions")
    op.drop_table("plans")
