"""
Pydantic request and response schemas for the Production AI Platform API.

Responsibilities:

- Validate incoming client requests.
- Define consistent API response models.
- Provide automatic OpenAPI documentation.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import (
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    field_validator,
)

from rag.models import DocumentType


class RegisterRequest(BaseModel):
    """
    Request payload for creating an organization and its first user.
    """

    organization_name: str = Field(
        ...,
        min_length=2,
        max_length=255,
        description="Name of the organization to create.",
        examples=["Acme AI"],
    )

    email: EmailStr = Field(
        ...,
        description="Email address for the new user.",
        examples=["owner@example.com"],
    )

    password: str = Field(
        ...,
        min_length=12,
        max_length=128,
        description=(
            "Password for the new account. Must contain at least 12 characters."
        ),
    )

    @field_validator("organization_name")
    @classmethod
    def validate_organization_name(
        cls,
        value: str,
    ) -> str:
        """
        Normalize and validate the organization name.
        """

        value = value.strip()

        if len(value) < 2:
            raise ValueError(
                "Organization name must contain at least 2 characters."
            )

        return value


class LoginRequest(BaseModel):
    """
    Request payload for authenticating an existing user.
    """

    email: EmailStr = Field(
        ...,
        description="Account email address.",
        examples=["owner@example.com"],
    )

    password: str = Field(
        ...,
        min_length=1,
        max_length=128,
        description="Account password.",
    )


class TokenResponse(BaseModel):
    """
    Bearer access token returned after successful authentication.
    """

    access_token: str = Field(
        ...,
        description="Signed JWT access token.",
    )

    token_type: str = Field(
        default="bearer",
        description="Authentication scheme for the token.",
    )


class UserResponse(BaseModel):
    """
    Public representation of an authenticated user.
    """

    id: UUID
    organization_id: UUID
    email: EmailStr
    is_active: bool

    model_config = ConfigDict(
        from_attributes=True,
    )


class DocumentResponse(BaseModel):
    """
    Public metadata for a tenant-owned uploaded document.

    Internal storage locations are intentionally not exposed.
    """

    id: UUID
    organization_id: UUID
    uploaded_by_user_id: UUID | None
    original_filename: str
    content_type: str
    size_bytes: int
    document_type: DocumentType
    status: str
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(
        from_attributes=True,
    )


class ChatRequest(BaseModel):
    """
    Request payload for the chat endpoint.
    """

    question: str = Field(
        ...,
        min_length=1,
        max_length=4000,
        description="The user's question.",
        examples=["Explain Python decorators."],
    )

    turnstile_token: str = Field(
        ...,
        min_length=1,
        max_length=2048,
        description=(
            "Single-use Cloudflare Turnstile verification token."
        ),
    )

    session_id: str | None = Field(
        default=None,
        min_length=1,
        max_length=128,
        description=(
            "Optional conversation identifier. "
            "A server-generated identifier is returned "
            "when omitted."
        ),
        examples=["user-123"],
    )

    use_cache: bool = Field(
        default=True,
        description="Whether cached responses may be used.",
    )


class Source(BaseModel):
    """
    Information about a retrieved source document.
    """

    document: str = Field(
        ...,
        description="Document filename or identifier.",
    )

    score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Cross-encoder relevance score.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional document metadata.",
    )


class ChatResponse(BaseModel):
    """
    Response returned from the chat endpoint.
    """

    answer: str = Field(
        ...,
        description="Final answer generated by the LLM.",
    )

    sources: list[Source] = Field(
        default_factory=list,
        description="Retrieved supporting sources.",
    )

    session_id: str = Field(
        ...,
        description=(
            "Conversation identifier used for this request. "
            "Send it with subsequent requests to preserve "
            "history."
        ),
    )

    cached: bool = Field(
        default=False,
        description="True if the answer came from the response cache.",
    )

    grounded: bool = Field(
        default=False,
        description=(
            "Whether the answer is supported by returned "
            "knowledge-base sources and is not a refusal."
        ),
    )

    latency_ms: float = Field(
        ...,
        ge=0,
        description="End-to-end processing time in milliseconds.",
    )

    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "answer": (
                    "A decorator is a callable that wraps another function."
                ),
                "sources": [
                    {
                        "document": "python_decorators.md",
                        "score": 0.97,
                        "metadata": {
                            "page": 1,
                            "source": "docs",
                        },
                    }
                ],
                "session_id": "user-123",
                "cached": False,
                "grounded": True,
                "latency_ms": 842.6,
            }
        },
    )


class HealthResponse(BaseModel):
    """
    Health check response.
    """

    status: str = Field(
        ...,
        examples=["healthy"],
    )

    version: str = Field(
        ...,
        examples=["1.0.0"],
    )


class ErrorResponse(BaseModel):
    """
    Standard API error response.
    """

    detail: str = Field(
        ...,
        description="Human-readable error message.",
    )
